name: Deploy

on:  
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        repository: ${{github.repository}}
        token: ${{secrets.PAT}}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: "."
        target: ${{secrets.THE_PATH}}

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
            cd ${{secrets.THE_PATH}}
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh   
            npm i
            npm run build
            sysctemctl restart nginx